### ISSUE TITLE
Comment-User model: call relations

### ISSUE THREAD

**Issue by Grazouillis** [mll-lab/laravel-comment#8]
Hello,

First, thank you for providing this nice Laravel package.

Then, I have a tiny call for help to put to you:
From your suggestion, I started my **Comment** model like this: 

```
namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Actuallymab\LaravelComment\Models\Comment as LaravelComment;

// class Comment extends Model
final class Comment extends LaravelComment
```

But I'm surprised to notice that my relations don't work
From **Comment** model
```
    public function user()
    {
        return $this->belongsTo(User::class);
    }
```

From **User** model

```
 public function comments()
{
    return $this->hasMany(Comment::class);
}

```

From **Post** model

```
 public function comments()
{
    return $this->hasMany(Comment::class);
}

```

When I try to load the comments I saved thanks to your library, I call $comment->user->name in vain.
Could you provide me any help about what I am supposed to do ?
When I explore your code, I'm lost because I'm unfamiliar with polymorphic relations...

Thank you very much

**Comment by spawnia** [comment]
The relation is defined like this: https://github.com/mll-lab/laravel-comment/blob/decdf370db39d728851e5be60126d896c24b20d4/src/HasComments.php#L14-L17
